version: '3.7'

services:
    nuxt-app:
        build: ./
        container_name: nuxt-app
        restart: always
        ports:
            - '3000:3000'
        networks:
            - nuxt-network
networks:
    nuxt-network:
        driver: bridge
