name: GitHub Deploy Frontend
run-name: ${{ github.actor }} Deploys Frontend
on:
    push:
        branches:
            - main
            - 'releases/**'
jobs:
    GitHub-Deploy-Frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
            - run: git config --global user.email "${GITHUB_ACTOR}"
            - run: git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
            - run: npm install
            - run: npm run build
            - run: npm run test
            - name: deploy frontend
              run: |
                  cd ./frontend
                  set -e
                  npm run build
                  cd dist
                  git add -A
                  echo > .nojekyll
                  git init
                  git checkout -B main
                  git add -A
                  git commit -m 'deploy'
                  git remote set-url "origin" "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
                  git push main:gh-pages
                  cd -
