name: GitHub Deploy Frontend
run-name: ${{ github.actor }} Deploys Frontend
on:
    push:
        branches:
            - main
            - 'releases/**'
jobs:
    Deploy-And-Test-Frontend:
        runs-on:
        group: ubuntu-runners
        labels: ubuntu-20.04-16core
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
              steps:
                  - run: npm run test
                  - run: npm run deployFrontend
